version: "3"
services:
  user_hobbies:
    container_name: user_hobbies
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "80:80"
      # - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: user_hobbies
    volumes:
      - data-volume:/data/db
volumes:
  data-volume:
